version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: exploreindo_api
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./model:/app/model:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - exploreindo_network

  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    container_name: exploreindo_website
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - exploreindo_network

  nginx:
    image: nginx:alpine
    container_name: exploreindo_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
      - website
    restart: unless-stopped
    networks:
      - exploreindo_network

networks:
  exploreindo_network:
    driver: bridge

volumes:
  model_data:
    driver: local